### PR TITLE
chore: re-work some of the tests

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This is like 99% home :)  I'm having some struggles figuring out the failing kitchen sink test.  Ready for a first look.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@stephenplusplus I have a few questions about the code in here that I think may be easier to discuss over a GVC.  You have any time this afternoon or tomorrow to chat?

**Comment by stephenplusplus** [comment]
@JustinBeckwith I pushed a commit that is probably the source of the issue. I'm not sure what's going on, which you can read from the console.log's :) The behavior of cork- and uncorking seems to not be working as expected. Leaving it here in case you have any ideas, otherwise I'll look into it as time permits!

**Comment by JustinBeckwith** [comment]
@stephenplusplus I decided to do this in 2 parts.  This part will just work the tests so that the next part  is easier :)

**Comment by JustinBeckwith** [comment]
*gentle ping*

**Pull request merged**
