### PR TITLE
Merge `next` into `master`

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This should be done as a rebase commit :)

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Should we enable `rebase and merge` commits for merges like this one?

**Comment by stephenplusplus** [comment]
Sorry for the gitfusion, but why not squash and merge?

**Comment by JustinBeckwith** [comment]
With squash and merge, we'll just get a single commit in master that shows "Merge from next to master", or something like that.  We want to retain the two commits that were made in the `next` branch, because they were distinct changes.  Essentially - we want to preserve history.

**Comment by JustinBeckwith** [comment]
In the general sense, PRs should be "squash and merge", as they typically do one thing.  Rebasing from a next branch to master is pretty much the only case I can think of where rebase and merge is appropriate.

**Comment by stephenplusplus** [comment]
Gotcha, that makes sense. Enabled, then I will disable!

**Pull request merged**
