### PR TITLE
delete config when it is probably wrong

### LINKED ISSUE #9: configstore caused uploads to fail
Unfortunately I don't have any useful logs or error messages, but when using gcs-resumable-upload by way of gcloud-node I kept getting a "Not found" error when running as one user, but not as another user on the same machine. Without fully understanding what configstore is there for, I went ahead and deleted the `~/.config/configstore/gcs-resumable-upload.json` file, and suddenly uploads started working again! I wish I had looked at the contents of the configstore file before I did it, but my guess is that some invalid config was saved and needed to be rejiggered for anything with gcs-resumable-upload to work. 

I think it would be good if there was some sanity check before doing anything with the contents of that file. I have a cron job running every minute overwriting the same file over and over again, so there was probably some old invalid data in configstore that kept getting reused over and over because the job always uses the same filename.

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #9

As described in #9, it's possible for the data stored inside of the config file to become inaccurate. This could make it look like we should attempt to resume an upload, when in fact, there isn't an upload to resume and instead, we should be restarting one.

Instead of always returning a 404 from the `continueUploading` process (i.e., the server tells us "That's not a file, what are you talking about?"), we will only return that error if the user gave us the resumable URI themselves. When we use the config file to get the URI, we'll just assume that means we failed to clean up after ourselves (or some other uncontrollable event intervened) and we can safely restart the upload.

@richardkazuomiller PTAL (please take a look)!

### CODE REVIEW

**Comment by stephenplusplus** [comment]
// @callmehiphop

**Comment by richardkazuomiller** [comment]
LGTM!

**Comment by stephenplusplus** [comment]
Thanks! Released under v0.4.3

**Comment by callmehiphop** [comment]
:+1:

**Pull request merged**
