### PR TITLE
chore: remove through2

### PR DESCRIPTION
**Pull request by JustinBeckwith**

### CODE REVIEW

**Comment by stephenplusplus** [comment]
image

**Comment by JustinBeckwith** [comment]
Ok apparently I need to actually think this one through2 :)

**Comment by stephenplusplus** [comment]
Maybe we actually want a PassThrough in places where we’re not doing anything?

**Comment by JustinBeckwith** [comment]
meh, ain't worth it atm

**Comment by stephenplusplus** [comment]
I deleted, then brought it back-- do you want to save the progress in that branch, or can we kill it?

**Comment by JustinBeckwith** [comment]
nah just kill it dead

**Pull request closed without merging**
