### PR TITLE
Added support for file size specification in resumable upload URLs

### PR DESCRIPTION
**Pull request by ryankurte**
Mapping from metadata.contentLength to X-Upload-Content-Length header to specify upload file size.

### CODE REVIEW

**Comment by ryankurte** [comment]
Travis failing at nvm install step, not sure how to fix that :-/

**Comment by stephenplusplus** [comment]
Thank you!

**Comment by stephenplusplus** [comment]
Released under v0.4.2

**Comment by ryankurte** [comment]
No worries, thanks for the quick release!

**Pull request closed without merging**
