### PR TITLE
chore: enable noImplicitAny

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This is very rough, but it lets us enable noImplicitAny.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@stephenplusplus not sure what's up with the CircleCi failures :(

**Comment by stephenplusplus** [comment]
Oh good, I was looking forward to having another battle with Circle! Let me take a quick look 🥊

**Comment by stephenplusplus** [comment]
Oh, it could be because you're on a fork, and we use an encrypted env var to decode the key. Let me see if I can just split the tests real quick, so that they won't fail on PRs.

**Comment by JustinBeckwith** [comment]
Got this working on the other PR :D  Over to #37 ....

**Pull request closed without merging**
